name: Rust

env:
    PACKAGE_NAME: xtc

on:
  push:
    tags:
      - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        env:
          target: x86_64-unknown-linux-musl
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install toolchain
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                target: ${{ env.target }}
                default: true
                override: true
            - name: Build
              run: cargo build --release && strip target/release/${{ env.PACKAGE_NAME }} && tar czvf target/release/${{ env.PACKAGE_NAME }}-${{ github.event.release.tag_name }}-${{ env.target }}.tar.gz target/release/${{ env.PACKAGE_NAME }}
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: |
                  target/release/${{ env.PACKAGE_NAME }}-${{ github.event.release.tag_name }}-${{ env.target }}.tar.gz
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    build-win:
        runs-on: windows-latest
        env:
          target: x86_64-pc-windows-msvc
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install toolchain
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                target: ${{ env.target }}
                default: true
                override: true
            - name: Build
              uses: actions-rs/cargo@v1
              with:
                command: build
                args: --release
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: |
                  target/release/${{ env.PACKAGE_NAME }}.exe
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    build-mac:
        runs-on: macos-latest
        env:
          target: x86_64-apple-darwin
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install toolchain
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                target: ${{ env.target }}
                default: true
                override: true
            - name: Build
              run: cargo build --release && strip target/release/${{ env.PACKAGE_NAME }} && tar czvf target/release/${{ env.PACKAGE_NAME }}-${{ github.event.release.tag_name }}-${{ env.target }}.tar.gz target/release/${{ env.PACKAGE_NAME }}
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: |
                  target/release/${{ env.PACKAGE_NAME }}-${{ github.event.release.tag_name }}-${{ env.target }}.tar.gz
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}